### ISSUE TITLE
Cannot run `eb local run` using Python 3.7

### ISSUE THREAD

**Issue by jasonrhaas** [aws/aws-elastic-beanstalk-cli#25] opened 2020-04-18 18:55 UTC
### Description

Cannot run `eb local run` using Python 3.7 Amazon Linux 2 environment.

### Steps to reproduce

`eb init` using python 3.7
`eb run local`

### Observed result

```
2.11.4 running Ruby 2.3 (Puma)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.11.4 running Ruby 2.2 (Puma)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.11.4 running Ruby 2.1 (Puma)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.11.4 running Ruby 2.0 (Puma)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v3.3.4 running Tomcat 8.5 Java 8', 'PermittedFileTypes': ['war', 'zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v3.3.4 running Tomcat 8 Java 8', 'PermittedFileTypes': ['war', 'zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v3.3.4 running Tomcat 7 Java 7', 'PermittedFileTypes': ['war', 'zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v3.3.4 running Tomcat 7 Java 6', 'PermittedFileTypes': ['war', 'zip']}, {'SolutionStackName': '64bit Windows Server Core 2019 v2.5.2 running IIS 10.0', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server 2019 v2.5.2 running IIS 10.0', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server Core 2016 v2.5.2 running IIS 10.0', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server 2016 v2.5.2 running IIS 10.0', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server Core 2012 R2 v2.5.2 running IIS 8.5', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server 2012 R2 v2.5.2 running IIS 8.5', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server Core 2016 v1.2.0 running IIS 10.0', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server 2016 v1.2.0 running IIS 10.0', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server Core 2012 R2 v1.2.0 running IIS 8.5', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server 2012 R2 v1.2.0 running IIS 8.5', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server 2012 v1.2.0 running IIS 8', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server Core 2012 R2 running IIS 8.5', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server 2012 R2 running IIS 8.5', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server 2012 running IIS 8', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.14.3 running Docker 18.09.9-ce', 'PermittedFileTypes': []}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.20.0 running Multi-container Docker 18.09.9-ce (Generic)', 'PermittedFileTypes': ['zip', 'json']}, {'SolutionStackName': '64bit Debian jessie v2.14.3 running Go 1.4 (Preconfigured - Docker)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Debian jessie v2.14.3 running Go 1.3 (Preconfigured - Docker)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Debian jessie v2.14.3 running Python 3.4 (Preconfigured - Docker)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v3.0.0 running Docker', 'PermittedFileTypes': []}, {'SolutionStackName': '64bit Amazon Linux 2 v3.0.0 running Python 3.7', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v3.0.0 running Corretto 11', 'PermittedFileTypes': ['jar', 'zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v3.0.0 running Corretto 8', 'PermittedFileTypes': ['jar', 'zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v0.1.0 running PHP 7.4 (BETA)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v0.1.0 running PHP 7.3 (BETA)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v0.1.0 running PHP 7.2 (BETA)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v0.1.0 running Node.js 12 (BETA)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v0.1.0 running Node.js 10 (BETA)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v0.1.0 running Go 1 (BETA)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v0.1.0 running Ruby 2.7 (BETA)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v0.1.0 running Ruby 2.6 (BETA)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v0.1.0 running Ruby 2.5 (BETA)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.10.4 running Java 8', 'PermittedFileTypes': ['jar', 'zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.10.4 running Java 7', 'PermittedFileTypes': ['jar', 'zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.15.1 running Go 1.14.1', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.6.20 running Packer 1.0.3', 'PermittedFileTypes': []}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.14.3 running GlassFish 5.0 Java 8 (Preconfigured - Docker)', 'PermittedFileTypes': ['zip']}], 'ResponseMetadata': {'RequestId': '810fca50-e016-4de3-8d6b-9497e3bea040', 'HTTPStatusCode': 200, 'date': 'Sat, 18 Apr 2020 18:53:07 GMT', 'RetryAttempts': 0}}
2020-04-18 13:53:08,419 (DEBUG) ebcli.lib.elasticbeanstalk : Solution Stack result size = 70
2020-04-18 13:53:08,433 (DEBUG) ebcli.lib.elasticbeanstalk : Inside list_platform_versions api wrapper
2020-04-18 13:53:08,434 (DEBUG) ebcli.lib.aws : Making api call: (elasticbeanstalk, list_platform_versions) to region: us-west-2 with args:{'Filters': [{'Type': 'PlatformOwner', 'Operator': '=', 'Values': ['self']}]}
2020-04-18 13:53:08,580 (DEBUG) ebcli.lib.aws : API call finished, status = 200
2020-04-18 13:53:08,580 (DEBUG) ebcli.lib.aws : Response: {'PlatformSummaryList': [], 'ResponseMetadata': {'RequestId': '67a8c525-c0f5-4d0b-b76f-97d046e02f43', 'HTTPStatusCode': 200, 'date': 'Sat, 18 Apr 2020 18:53:08 GMT', 'RetryAttempts': 0}}
2020-04-18 13:53:08,587 (INFO) eb : Traceback (most recent call last):
  File "/Users/jhaas/.local/share/virtualenvs/bazze-marketplace-RumDEcI_/lib/python3.7/site-packages/ebcli/containers/factory.py", line 115, in _get_solution_stack
    soln_stk = solution_stack_ops.find_solution_stack_from_string(solution_string)
  File "/Users/jhaas/.local/share/virtualenvs/bazze-marketplace-RumDEcI_/lib/python3.7/site-packages/ebcli/operations/solution_stack_ops.py", line 103, in find_solution_stack_from_string
    raise NotFoundError(alerts['platform.invalidstring'].format(solution_string))
ebcli.objects.exceptions.NotFoundError: Elastic Beanstalk can't find a platform version that matches "Python 3.7 running on 64bit Amazon Linux 2".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jhaas/.local/share/virtualenvs/bazze-marketplace-RumDEcI_/lib/python3.7/site-packages/ebcli/core/ebrun.py", line 62, in run_app
    app.run()
  File "/Users/jhaas/.local/share/virtualenvs/bazze-marketplace-RumDEcI_/lib/python3.7/site-packages/cement/core/foundation.py", line 797, in run
    return_val = self.controller._dispatch()
  File "/Users/jhaas/.local/share/virtualenvs/bazze-marketplace-RumDEcI_/lib/python3.7/site-packages/cement/core/controller.py", line 472, in _dispatch
    return func()
  File "/Users/jhaas/.local/share/virtualenvs/bazze-marketplace-RumDEcI_/lib/python3.7/site-packages/cement/core/controller.py", line 472, in _dispatch
    return func()
  File "/Users/jhaas/.local/share/virtualenvs/bazze-marketplace-RumDEcI_/lib/python3.7/site-packages/cement/core/controller.py", line 478, in _dispatch
    return func()
  File "/Users/jhaas/.local/share/virtualenvs/bazze-marketplace-RumDEcI_/lib/python3.7/site-packages/ebcli/core/abstractcontroller.py", line 92, in default
    self.do_command()
  File "/Users/jhaas/.local/share/virtualenvs/bazze-marketplace-RumDEcI_/lib/python3.7/site-packages/ebcli/controllers/local.py", line 64, in do_command
    self.app.pargs.allow_insecure_ssl)
  File "/Users/jhaas/.local/share/virtualenvs/bazze-marketplace-RumDEcI_/lib/python3.7/site-packages/ebcli/containers/factory.py", line 45, in make_container
    soln_stk = _get_solution_stack()
  File "/Users/jhaas/.local/share/virtualenvs/bazze-marketplace-RumDEcI_/lib/python3.7/site-packages/ebcli/containers/factory.py", line 121, in _get_solution_stack
    raise NotFoundError('Solution stack {} does not appear to be valid'.format(solution_string))
ebcli.objects.exceptions.NotFoundError: Solution stack Python 3.7 running on 64bit Amazon Linux 2 does not appear to be valid
```

### Expected result

Should be able to run elastic beanstalk locally in docker.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS

`Add --debug flag to command you are running`

**Comment by halcarleton** [comment] 2020-04-20 17:13
Hi @jasonrhaas , thanks for reporting this.

Could you provide the following information?
* EB-CLI version
* Application region

Thanks

**Comment by rupe120** [comment] 2020-04-27 15:22
I'm running into the same issue

EB-CLI version: 3.18.0 (Python 3.8.2)
Region: us-east-1

**Comment by halcarleton** [comment] 2020-04-27 17:46
Thank you for the information @rupe120. We are actively investigating this issue.

Could you provide a couple additional pieces of information when you have a chance?

* exact commands that were run to reproduce the issue
* the value of `default_platform` in your `.elasticbeanstalk/config` file

Thanks

**Comment by rupe120** [comment] 2020-04-27 20:06
`eb init --profile sandbox`

I chose:
- us-east-1 : US East (N. Virginia)
- Create new Application
- Default application name
- Python
- Python 3.7 running on 64bit Amazon Linux 2
- Yes, setup SSH
- Chose my key

`eb create -t worker`

I chose:
- Default environment name
- No Spot Fleet
- Yes download sample application

`eb local run`

    ERROR: NotFoundError - Solution stack Python 3.7 running on 64bit Amazon Linux 2 does not appear to be valid

The `default_platform` is "Python 3.7 running on 64bit Amazon Linux 2"

**Comment by halcarleton** [comment] 2020-04-27 20:56
Thanks for the info @rupe120, that is very helpful. I have verified the bug and am working on a fix.

One thing to note, `eb local run` is not officially supported on Windows. Additionally it only supports docker platforms so "Python 3.7 running on 64bit Amazon Linux 2" will continue to fail once this bug is resolved. [More info here.](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb3-local.html)

This bug was introduced in the latest release, so if you would like to continue to use this functionality while waiting for a fix to be released you can downgrade awsebcli to version 3.17.1. If you do this you will need to re-initialize any applications directories that were initialized with 3.18.0.

I will leave this issue open while the fix is pending release.

**Comment by rupe120** [comment] 2020-04-28 16:00
I switched over to testing this under Ubuntu and I'm getting inconsistent results. I initially had to go all the way back to 3.13.0 before I got a different error message, but then I started receiving the same `Solution stack does not appear to be valid` message even with that version

**Comment by halcarleton** [comment] 2020-04-28 16:45
This is likely because you did not fully reinitialize the application directory. I should have clarified that more. Just rerunning `eb init` is not enough, you will need to delete `.elasticbeanstalk/config` and then rerun `eb init`.

Alternatively, in this case, you could just change the `default_platform` value within `.elasticbeanstalk/config` to null then rerun `eb init`.

**Comment by rupe120** [comment] 2020-04-28 18:13
Nulling the platform got me past that error, though I'm still not able to perform a `local run`

I created a new EB application following the same steps I outlined above with version 3.17.1, and when I tried to perform a `local run` imediately after I recieved:

    ERROR: NotSupportedError - You can use "eb local" only with preconfigured, generic and multicontainer Docker platforms.

**Comment by halcarleton** [comment] 2020-04-28 20:08
Correct, `eb local run` only works with docker platforms. This is expected behavior.

Please see [my previous comment](https://github.com/aws/aws-elastic-beanstalk-cli/issues/25#issuecomment-620229908):
> Additionally it only supports docker platforms, so "Python 3.7 running on 64bit Amazon Linux 2" will continue to fail once this bug is resolved.

**Comment by km2411** [comment] 2020-05-16 15:08
While experimenting with a Multi-container application, I faced the similar issue but downgrading from 3.18.0 to 3.17.1 worked. Thanks @halcarleton

**Comment by halcarleton** [comment] 2020-07-21 22:51
This should be fixed in [v3.18.2](https://pypi.org/project/awsebcli/3.18.2/)

**Closed by halcarleton** 2020-07-21 22:51 UTC
Labels: bug

**Comment by jakubLangr** [comment] 2022-03-19 19:09
Hi @halcarleton and @km2411 

I just got this issue on `3.20.0` when running a freshly `init`'d and `create`'d app, when I run:
` eb local run --debug`
I get:
```
2022-03-19 19:08:43,660 (INFO) eb : Traceback (most recent call last):
  File "/home/jakub/.local/lib/python3.9/site-packages/ebcli/containers/commands.py", line 286, in _run_live
    return utils.exec_cmd_live_output(args)
  File "/home/jakub/.local/lib/python3.9/site-packages/ebcli/lib/utils.py", line 232, in exec_cmd
    raise CommandError(error_msg, output_str, returncode)
ebcli.objects.exceptions.CommandError: Exited with return code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jakub/.local/lib/python3.9/site-packages/ebcli/core/ebrun.py", line 62, in run_app
    app.run()
  File "/home/jakub/miniconda3/envs/e39/lib/python3.9/site-packages/cement/core/foundation.py", line 797, in run
    return_val = self.controller._dispatch()
  File "/home/jakub/miniconda3/envs/e39/lib/python3.9/site-packages/cement/core/controller.py", line 472, in _dispatch
    return func()
  File "/home/jakub/miniconda3/envs/e39/lib/python3.9/site-packages/cement/core/controller.py", line 472, in _dispatch
    return func()
  File "/home/jakub/miniconda3/envs/e39/lib/python3.9/site-packages/cement/core/controller.py", line 478, in _dispatch
    return func()
  File "/home/jakub/.local/lib/python3.9/site-packages/ebcli/core/abstractcontroller.py", line 92, in default
    self.do_command()
  File "/home/jakub/.local/lib/python3.9/site-packages/ebcli/controllers/local.py", line 66, in do_command
    cnt.start()
  File "/home/jakub/.local/lib/python3.9/site-packages/ebcli/containers/abstractcontainer.py", line 66, in start
    self._pull()
  File "/home/jakub/.local/lib/python3.9/site-packages/ebcli/containers/abstractcontainer.py", line 122, in _pull
    return commands.pull_img(self._get_full_docker_path())
  File "/home/jakub/.local/lib/python3.9/site-packages/ebcli/containers/commands.py", line 46, in pull_img
    _pull_img(img)
  File "/home/jakub/.local/lib/python3.9/site-packages/ebcli/containers/commands.py", line 215, in _pull_img
    return _run_live(args)
  File "/home/jakub/.local/lib/python3.9/site-packages/ebcli/containers/commands.py", line 288, in _run_live
    _handle_command_error(e)
  File "/home/jakub/.local/lib/python3.9/site-packages/ebcli/containers/commands.py", line 297, in _handle_command_error
    raise CommandError
ebcli.objects.exceptions.CommandError: None

```

**Comment by BlazingRockStorm** [comment] 2022-11-11 08:44
I'm using the demo app in this instruction https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker-eblocal.html and get the error too. Here's the log:
```
2022-11-11 17:33:32,742 (DEBUG) cement.core.foundation : laying cement for the 'eb' application
2022-11-11 17:33:32,742 (DEBUG) cement.core.hook : defining hook 'pre_setup'
2022-11-11 17:33:32,742 (DEBUG) cement.core.hook : defining hook 'post_setup'
2022-11-11 17:33:32,742 (DEBUG) cement.core.hook : defining hook 'pre_run'
2022-11-11 17:33:32,742 (DEBUG) cement.core.hook : defining hook 'post_run'
2022-11-11 17:33:32,742 (DEBUG) cement.core.hook : defining hook 'pre_argument_parsing'
2022-11-11 17:33:32,742 (DEBUG) cement.core.hook : defining hook 'post_argument_parsing'
2022-11-11 17:33:32,742 (DEBUG) cement.core.hook : defining hook 'pre_close'
2022-11-11 17:33:32,742 (DEBUG) cement.core.hook : defining hook 'post_close'
2022-11-11 17:33:32,742 (DEBUG) cement.core.hook : defining hook 'signal'
2022-11-11 17:33:32,742 (DEBUG) cement.core.hook : defining hook 'pre_render'
2022-11-11 17:33:32,742 (DEBUG) cement.core.hook : defining hook 'post_render'
2022-11-11 17:33:32,742 (DEBUG) cement.core.hook : registering hook 'add_handler_override_options' from cement.core.foundation into hooks['post_setup']
2022-11-11 17:33:32,742 (DEBUG) cement.core.hook : registering hook 'handler_override' from cement.core.foundation into hooks['post_argument_parsing']
2022-11-11 17:33:32,742 (DEBUG) cement.core.handler : defining handler type 'extension' (IExtension)
2022-11-11 17:33:32,742 (DEBUG) cement.core.handler : defining handler type 'log' (ILog)
2022-11-11 17:33:32,742 (DEBUG) cement.core.handler : defining handler type 'config' (IConfig)
2022-11-11 17:33:32,742 (DEBUG) cement.core.handler : defining handler type 'mail' (IMail)
2022-11-11 17:33:32,742 (DEBUG) cement.core.handler : defining handler type 'plugin' (IPlugin)
2022-11-11 17:33:32,743 (DEBUG) cement.core.handler : defining handler type 'output' (IOutput)
2022-11-11 17:33:32,743 (DEBUG) cement.core.handler : defining handler type 'argument' (IArgument)
2022-11-11 17:33:32,743 (DEBUG) cement.core.handler : defining handler type 'controller' (IController)
2022-11-11 17:33:32,743 (DEBUG) cement.core.handler : defining handler type 'cache' (ICache)
2022-11-11 17:33:32,743 (DEBUG) cement.core.handler : registering handler '<class 'cement.core.extension.CementExtensionHandler'>' into handlers['extension']['cement']
2022-11-11 17:33:32,762 (DEBUG) cement.ext.ext_plugin : plugin config dir /etc/eb/plugins.d does not exist.
2022-11-11 17:33:32,762 (DEBUG) cement.ext.ext_plugin : plugin config dir /Users/user/.eb/plugins.d does not exist.
2022-11-11 17:33:32,770 (DEBUG) ebcli.core.hooks : -- EBCLI Version: 3.20.3
2022-11-11 17:33:32,770 (DEBUG) ebcli.core.hooks : -- Python Version: 3.10.8 (main, Oct 13 2022, 10:17:43) [Clang 14.0.0 (clang-1400.0.29.102)]
2022-11-11 17:33:32,770 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/user/eb-docker-nginx-proxy-master
2022-11-11 17:33:32,773 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/user/eb-docker-nginx-proxy-master
2022-11-11 17:33:32,775 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/user/eb-docker-nginx-proxy-master
2022-11-11 17:33:32,777 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/user/eb-docker-nginx-proxy-master
2022-11-11 17:33:32,779 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/user/eb-docker-nginx-proxy-master
2022-11-11 17:33:32,782 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/user/eb-docker-nginx-proxy-master
2022-11-11 17:33:32,785 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/user/eb-docker-nginx-proxy-master
2022-11-11 17:33:32,788 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/user/eb-docker-nginx-proxy-master
2022-11-11 17:33:32,790 (DEBUG) ebcli.lib.utils : docker --version
2022-11-11 17:33:33,034 (DEBUG) ebcli.lib.utils : Docker version 20.10.20, build 9fdeb9c

2022-11-11 17:33:33,042 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/user/eb-docker-nginx-proxy-master
2022-11-11 17:33:33,045 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/user/eb-docker-nginx-proxy-master
2022-11-11 17:33:33,047 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/user/eb-docker-nginx-proxy-master
2022-11-11 17:33:33,049 (DEBUG) ebcli.lib.elasticbeanstalk : Inside list_platform_branches api wrapper
2022-11-11 17:33:33,049 (DEBUG) ebcli.lib.aws : Creating new Botocore Session
2022-11-11 17:33:33,049 (DEBUG) ebcli.lib.aws : Botocore version: 1.23.54
2022-11-11 17:33:33,058 (DEBUG) ebcli.lib.aws : Creating new Botocore Client for elasticbeanstalk
2022-11-11 17:33:33,141 (DEBUG) ebcli.lib.aws : Successfully created session for elasticbeanstalk
2022-11-11 17:33:33,141 (DEBUG) ebcli.lib.aws : Making api call: (elasticbeanstalk, list_platform_branches) to region: ap-northeast-1 with args:{'Filters': [{'Attribute': 'BranchName', 'Operator': '=', 'Values': ['ECS running on 64bit Amazon Linux 2']}]}
2022-11-11 17:33:33,229 (DEBUG) ebcli.lib.aws : API call finished, status = 200
2022-11-11 17:33:33,229 (DEBUG) ebcli.lib.aws : Response: {'PlatformBranchSummaryList': [{'PlatformName': 'Docker', 'BranchName': 'ECS running on 64bit Amazon Linux 2', 'BranchOrder': '10500', 'LifecycleState': 'Supported', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}], 'ResponseMetadata': {'RequestId': '1e28f7ca-619f-430c-9a3d-b310c8bf7c85', 'HTTPStatusCode': 200, 'date': 'Fri, 11 Nov 2022 08:33:32 GMT', 'RetryAttempts': 0}}
2022-11-11 17:33:33,230 (DEBUG) ebcli.lib.elasticbeanstalk : Inside list_platform_versions api wrapper
2022-11-11 17:33:33,230 (DEBUG) ebcli.lib.aws : Making api call: (elasticbeanstalk, list_platform_versions) to region: ap-northeast-1 with args:{'Filters': [{'Type': 'PlatformBranchName', 'Operator': '=', 'Values': ['ECS running on 64bit Amazon Linux 2']}]}
2022-11-11 17:33:33,310 (DEBUG) ebcli.lib.aws : API call finished, status = 200
2022-11-11 17:33:33,311 (DEBUG) ebcli.lib.aws : Response: {'PlatformSummaryList': [{'PlatformArn': 'arn:aws:elasticbeanstalk:ap-northeast-1::platform/ECS running on 64bit Amazon Linux 2/3.2.1', 'PlatformOwner': 'AWSElasticBeanstalk', 'PlatformStatus': 'Ready', 'PlatformCategory': 'ECS', 'OperatingSystemName': 'Amazon Linux', 'OperatingSystemVersion': '2', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP'], 'SupportedAddonList': ['Log/CloudWatch', 'Log/S3', 'Monitoring/Healthd', 'WorkerDaemon/SQSD'], 'PlatformLifecycleState': 'Recommended', 'PlatformVersion': '3.2.1', 'PlatformBranchName': 'ECS running on 64bit Amazon Linux 2', 'PlatformBranchLifecycleState': 'Supported'}], 'ResponseMetadata': {'RequestId': 'a3fc078a-45bb-4097-8a1b-459d41c5601d', 'HTTPStatusCode': 200, 'date': 'Fri, 11 Nov 2022 08:33:33 GMT', 'RetryAttempts': 0}}
2022-11-11 17:33:33,311 (DEBUG) ebcli.lib.elasticbeanstalk : Inside describe_platform_version api wrapper
2022-11-11 17:33:33,311 (DEBUG) ebcli.lib.aws : Making api call: (elasticbeanstalk, describe_platform_version) to region: ap-northeast-1 with args:{'PlatformArn': 'arn:aws:elasticbeanstalk:ap-northeast-1::platform/ECS running on 64bit Amazon Linux 2/3.2.1'}
2022-11-11 17:33:33,447 (DEBUG) ebcli.lib.aws : API call finished, status = 200
2022-11-11 17:33:33,447 (DEBUG) ebcli.lib.aws : Response: {'PlatformDescription': {'PlatformArn': 'arn:aws:elasticbeanstalk:ap-northeast-1::platform/ECS running on 64bit Amazon Linux 2/3.2.1', 'PlatformOwner': 'AWSElasticBeanstalk', 'PlatformName': 'ECS running on 64bit Amazon Linux 2', 'PlatformVersion': '3.2.1', 'SolutionStackName': '64bit Amazon Linux 2 v3.2.1 running ECS', 'PlatformStatus': 'Ready', 'DateCreated': datetime.datetime(2022, 11, 3, 17, 59, 2, 630000, tzinfo=tzutc()), 'DateUpdated': datetime.datetime(2022, 11, 5, 1, 52, 26, 10000, tzinfo=tzutc()), 'PlatformCategory': 'ECS', 'Description': '64bit Amazon Linux 2 running ECS', 'Maintainer': 'aws-elasticbeanstalk-platforms@amazon.com', 'OperatingSystemName': 'Amazon Linux', 'OperatingSystemVersion': '2', 'ProgrammingLanguages': [], 'Frameworks': [{'Name': 'ECS', 'Version': ''}], 'CustomAmiList': [{'VirtualizationType': 'pv', 'ImageId': ''}, {'VirtualizationType': 'hvm', 'ImageId': 'ami-03fe378c175d2ad9c'}], 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP'], 'SupportedAddonList': ['Log/CloudWatch', 'Log/S3', 'Monitoring/Healthd', 'WorkerDaemon/SQSD'], 'PlatformLifecycleState': 'Recommended', 'PlatformBranchName': 'ECS running on 64bit Amazon Linux 2', 'PlatformBranchLifecycleState': 'Supported'}, 'ResponseMetadata': {'RequestId': '8b788f1c-97ee-4590-95fe-4b6d435ddc7d', 'HTTPStatusCode': 200, 'date': 'Fri, 11 Nov 2022 08:33:32 GMT', 'RetryAttempts': 0}}
2022-11-11 17:33:33,448 (DEBUG) ebcli.lib.elasticbeanstalk : Inside list_platform_branches api wrapper
2022-11-11 17:33:33,448 (DEBUG) ebcli.lib.aws : Making api call: (elasticbeanstalk, list_platform_branches) to region: ap-northeast-1 with args:{'Filters': [{'Attribute': 'BranchName', 'Operator': '=', 'Values': ['ECS running on 64bit Amazon Linux 2']}]}
2022-11-11 17:33:33,503 (DEBUG) ebcli.lib.aws : API call finished, status = 200
2022-11-11 17:33:33,503 (DEBUG) ebcli.lib.aws : Response: {'PlatformBranchSummaryList': [{'PlatformName': 'Docker', 'BranchName': 'ECS running on 64bit Amazon Linux 2', 'BranchOrder': '10500', 'LifecycleState': 'Supported', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}], 'ResponseMetadata': {'RequestId': '5bba52f8-31e5-464a-9704-4c0352c6dd67', 'HTTPStatusCode': 200, 'date': 'Fri, 11 Nov 2022 08:33:33 GMT', 'RetryAttempts': 0}}
2022-11-11 17:33:33,512 (INFO) eb : Traceback (most recent call last):
  File "/usr/local/Cellar/aws-elasticbeanstalk/3.20.3_1/libexec/lib/python3.10/site-packages/ebcli/core/ebrun.py", line 62, in run_app
    app.run()
  File "/usr/local/Cellar/aws-elasticbeanstalk/3.20.3_1/libexec/lib/python3.10/site-packages/cement/core/foundation.py", line 797, in run
    return_val = self.controller._dispatch()
  File "/usr/local/Cellar/aws-elasticbeanstalk/3.20.3_1/libexec/lib/python3.10/site-packages/cement/core/controller.py", line 472, in _dispatch
    return func()
  File "/usr/local/Cellar/aws-elasticbeanstalk/3.20.3_1/libexec/lib/python3.10/site-packages/cement/core/controller.py", line 472, in _dispatch
    return func()
  File "/usr/local/Cellar/aws-elasticbeanstalk/3.20.3_1/libexec/lib/python3.10/site-packages/cement/core/controller.py", line 478, in _dispatch
    return func()
  File "/usr/local/Cellar/aws-elasticbeanstalk/3.20.3_1/libexec/lib/python3.10/site-packages/ebcli/core/abstractcontroller.py", line 92, in default
    self.do_command()
  File "/usr/local/Cellar/aws-elasticbeanstalk/3.20.3_1/libexec/lib/python3.10/site-packages/ebcli/controllers/local.py", line 62, in do_command
    cnt = factory.make_container(self.app.pargs.envvars,
  File "/usr/local/Cellar/aws-elasticbeanstalk/3.20.3_1/libexec/lib/python3.10/site-packages/ebcli/containers/factory.py", line 76, in make_container
    raise NotSupportedError(strings['local.unsupported'])
ebcli.objects.exceptions.NotSupportedError: You can use "eb local" only with preconfigured, generic and multicontainer Docker platforms.
```
