### ISSUE TITLE
Allow Latest Version of Botocore

### ISSUE THREAD

**Issue by abeerag** [aws/aws-elastic-beanstalk-cli#227] opened 2022-10-25 22:04 UTC
### Description
Its impossible to install the latest version of awscli and awsebcli in the same virtualenv

### Steps to reproduce

pip install awscli awsebcli

### Observed result

these package versions have conflicting dependencies.

The conflict is caused by:
    awscli 1.26.1 depends on botocore==1.28.1
    awsebcli 3.20.3 depends on botocore<1.24.0 and >1.23.41

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

### Expected result

Describe what you expected.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. EBCLI version:

**Comment by simonstewart** [comment] 2022-11-15 08:41
this is affecting us too

**Comment by gee-forr** [comment] 2022-11-15 08:50
@abeerag - here's what we've done so far:

We tried using this requirements.txt, which has a mutually compatible botocore, and the highest possible versions of each util, but

```
botocore==1.27.86
awscli==1.25.87
awsebcli==3.14.4
```

it crashes on install with a known PyYAML compilation error, due to the required PyYAML being too old. We were able to get around that by using an ancient version of Python -- 3.8.

Ultimately, we landed on using virtualenvs to run the 2 awscli utils independently. We can now use whatever version we require for each util, and they don't conflict. Give that a try for now.

(we've got other weird access issues when running `eb` but that's outside the scope of this particular issue)

**Comment by chadamski** [comment] 2023-01-04 22:11
This issue is also impacting us, and seems to be [referenced here as perpetually unresolved.](https://github.com/aws/aws-elastic-beanstalk-cli/issues/2)

**Comment by yohanthshetty** [comment] 2023-01-04 22:30
Hi @chadamski,
Apologies for the inconvenience.
I run `pip install awscli awsebcli` in the eb virtual environment and it works for me.
Did you try using the EB CLI installation scripts that you can find at [github-ebcli-setup](https://github.com/aws/aws-elastic-beanstalk-cli-setup). The setup scripts will remedy this by using a virtualenv for all eb-cli commands, so you won't run into this conflict moving forward.

**Comment by chadamski** [comment] 2023-01-05 16:26
Hi, @yohanthshetty -- I gave this a try and had some success after several rounds of trial and error, but am I understanding correctly that using two separate virtual environments in order to deploy to EB is supposed to be the long term solution? This seems like an inconvenient workaround rather than a fix.

**Comment by yohanthshetty** [comment] 2023-02-09 00:54
Apologies for the inconvenience caused. No, you shouldn't be requiring two separate virtual environments. 
<img width="543" alt="Screenshot 2023-02-08 at 16 43 15" src="https://user-images.githubusercontent.com/24809810/217685682-039ff026-a94b-4cda-9f5f-1a1ff8601d8c.png">
@chadamski I just tried it out on a single Virtual Machine. (Created a Virtual Environment from [here](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3-install-virtualenv.html) ) and then ran `pip install awscli awsebcli` in the active virtual env. As seen in the attached screenshot I was successfully able to install both together.
Could you please check the default python version that you are using in the venv? Might be something to do with a python version?
Please let me know if you can reproduce the error from scratch again with the steps I mentioned here.

**Comment by jsheld** [comment] 2023-03-09 22:29
Closing this issue as the customer has not indicated that this is still an issue.

**Closed by jsheld** 2023-03-09 22:29 UTC
