### ISSUE TITLE
'eb deploy' Docker multicontainer fails to update env: ECS error (Family can not be blank)

### ISSUE THREAD

**Issue by AndreLobato** [aws/aws-elastic-beanstalk-cli#7] opened 2020-01-27 02:52 UTC
### Description

On a Docker multi-container configuration, after have created the environment, on attempt to "eb deploy" to update I get this error from ECS:

```Service:AmazonECS, Code:InvalidParameterException, Message:Family can not be blank., Class:com.amazonaws.services.ecs.model.InvalidParameterException```

### Steps to reproduce

1. Create an Docker multi-container environment
2. Update the environment with "eb deploy"
Won't work and throw that error above

1. OS:
Tested on a couple of Linux/Ubuntu/Python distributions, versions:
Environments:
Python=2.7.6/3.5/3.6
awsebcli==3.17.0

**Comment by halcarleton** [comment] 2020-01-28 18:33
Hi @AndreLobato, thanks for reaching out.

I attempted to reproduce this issue yesterday and was unable to do so. Based on the nature of the error this issue does not appear to be with awsebcli, but we are not ruling it out quite yet.

As a first step to narrowing down the cause could you try deploying your application on the [Elastic Beanstalk console](https://console.aws.amazon.com/elasticbeanstalk) and see if you run into the same issue there?

Here is a [link to instructions](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.deploy-existing-version.html) for deployment via the Elastic Beanstalk console.

**Comment by AndreLobato** [comment] 2020-01-29 21:14
Hi @halcarleton, 

When trying to update the existing environment using the Console works as expected, also works when using a [GitHub Action](https://github.com/marketplace/actions/beanstalk-deploy) for handling EB deployments. 

It's only with `eb deploy` that I am noticing this issue.

Platform: Multi-container Docker 18.09.9-ce (Generic)
Region: us-east-1

If helps that's my env.yml file:

```
AWSConfigurationTemplateVersion: 1.1.0.0
OptionSettings:
    aws:elasticbeanstalk:application:
        Application Healthcheck URL: /api/status/
    aws:elb:loadbalancer:
        CrossZone: true
    aws:ec2:vpc:
        VPCId: -----------------
        Subnets: ------------------
        ELBSubnets: -----------------
        ELBScheme: internal
        AssociatePublicIpAddress: false
    aws:autoscaling:updatepolicy:rollingupdate:
        RollingUpdateEnabled: true
        MaxBatchSize: 2
        MinInstancesInService: 1
        RollingUpdateType: Immutable
    aws:elb:policies:
        ConnectionDrainingEnabled: true
    aws:elasticbeanstalk:healthreporting:system:
        SystemType: enhanced
    aws:elasticbeanstalk:environment:
        ServiceRole: aws-elasticbeanstalk-service-role
        LoadBalancerType: application
    aws:elasticbeanstalk:command:
        IgnoreHealthCheck: false
        DeploymentPolicy: Immutable
        BatchSizeType: Fixed
        BatchSize: 1
    aws:autoscaling:launchconfiguration:
        EC2KeyName: -----------------
        InstanceType: t3.micro
        IamInstanceProfile: aws-elasticbeanstalk-ec2-role
        SecurityGroups: -----------------
    aws:autoscaling:asg:
        MinSize: 1
        MaxSize: 2
    aws:elasticbeanstalk:application:environment:
       ....
Tags:
    ....
EnvironmentName: -----------------
EnvironmentTier: 
  Name: WebServer
  Type: Standard
```
Cheers!

**Comment by halcarleton** [comment] 2020-02-03 22:29
Hey @AndreLobato, I have been unable to reproduce this issue even with the additional information. If this continues to be an issue for you could you include an example application codebase(github repo or directory archive) which reproduces this issue and exact steps to reproduce?

Thanks

**Comment by halcarleton** [comment] 2020-02-24 23:08
Closing this issue as there has been no update for an extended period of time.

**Closed by halcarleton** 2020-02-24 23:08 UTC

**Comment by AndreLobato** [comment] 2021-08-19 04:45
Sorry again, Just a bit more context to this issue, looks like it happens when I try to "deploy" an "MultiDockerContainer" application, then EB will try to create a new ECS Task, however it seems that is missing to inherit the "[family](
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#standard_container_definition_params)" value from the previous task.
