### ISSUE TITLE
eb config put <Env_Name> returns Elastic Beanstalk can't find a platform version that matches "PHP 7.4 running on 64bit Amazon Linux 2".

### ISSUE THREAD

**Issue by ahmedkhammessi** [aws/aws-elastic-beanstalk-cli#62] opened 2021-02-08 14:43 UTC
### Description

I try to run eb config put to update a saved configuration after editing it localy.

### Steps to reproduce
```bash
eb init --profile ahmedkhamessi-devops
eb create dev-env

eb config save dev-env --cfg initial-configuration

eb setenv ENABLE_COOL_NEW_FEATURE=true

eb config save dev-env --cfg prod

#edited the prod.cfg.yml by adding autoscalingrules

finally run eb config put prod
```

### Observed result

2021-02-08 15:35:27,549 (DEBUG) cement.core.foundation : laying cement for the 'eb' application
2021-02-08 15:35:27,549 (DEBUG) cement.core.hook : defining hook 'pre_setup'
2021-02-08 15:35:27,550 (DEBUG) cement.core.hook : defining hook 'post_setup'
2021-02-08 15:35:27,550 (DEBUG) cement.core.hook : defining hook 'pre_run'
2021-02-08 15:35:27,550 (DEBUG) cement.core.hook : defining hook 'post_run'
2021-02-08 15:35:27,550 (DEBUG) cement.core.hook : defining hook 'pre_argument_parsing' 
2021-02-08 15:35:27,550 (DEBUG) cement.core.hook : defining hook 'post_argument_parsing'
2021-02-08 15:35:27,550 (DEBUG) cement.core.hook : defining hook 'pre_close'
2021-02-08 15:35:27,551 (DEBUG) cement.core.hook : defining hook 'post_close'
2021-02-08 15:35:27,551 (DEBUG) cement.core.hook : defining hook 'signal'
2021-02-08 15:35:27,551 (DEBUG) cement.core.hook : defining hook 'pre_render'
2021-02-08 15:35:27,551 (DEBUG) cement.core.hook : defining hook 'post_render'
2021-02-08 15:35:27,551 (DEBUG) cement.core.hook : registering hook 'add_handler_override_options' from cement.core.foundation into hooks['post_setup']
2021-02-08 15:35:27,551 (DEBUG) cement.core.hook : registering hook 'handler_override' from cement.core.foundation into hooks['post_argument_parsing']
2021-02-08 15:35:27,552 (DEBUG) cement.core.handler : defining handler type 'extension' (IExtension)
2021-02-08 15:35:27,552 (DEBUG) cement.core.handler : defining handler type 'log' (ILog)
2021-02-08 15:35:27,552 (DEBUG) cement.core.handler : defining handler type 'config' (IConfig)
2021-02-08 15:35:27,552 (DEBUG) cement.core.handler : defining handler type 'mail' (IMail)
2021-02-08 15:35:27,552 (DEBUG) cement.core.handler : defining handler type 'plugin' (IPlugin)
2021-02-08 15:35:27,552 (DEBUG) cement.core.handler : defining handler type 'output' (IOutput)
2021-02-08 15:35:27,552 (DEBUG) cement.core.handler : defining handler type 'argument' (IArgument)
2021-02-08 15:35:27,552 (DEBUG) cement.core.handler : defining handler type 'controller' (IController)
2021-02-08 15:35:27,553 (DEBUG) cement.core.handler : defining handler type 'cache' (ICache)
2021-02-08 15:35:27,553 (DEBUG) cement.core.handler : registering handler '<class 'cement.core.extension.CementExtensionHandler'>' into handlers['extension']['cement']
2021-02-08 15:35:27,572 (DEBUG) cement.ext.ext_plugin : plugin config dir /etc/eb/plugins.d does not exist.
2021-02-08 15:35:27,572 (DEBUG) cement.ext.ext_plugin : plugin config dir /home/ahmedkhamessi/.eb/plugins.d does not exist.
2021-02-08 15:35:27,582 (DEBUG) ebcli.core.hooks : -- EBCLI Version: 3.19.3
2021-02-08 15:35:27,582 (DEBUG) ebcli.core.hooks : -- Python Version: 3.8.2 (default, Jul 16 2020, 14:00:26)
[GCC 9.3.0]
2021-02-08 15:35:27,582 (DEBUG) ebcli.core.fileoperations : Project root found at: /home/ahmedkhamessi/aws/code/elastic-beanstalk/myapp
2021-02-08 15:35:27,586 (DEBUG) ebcli.core.fileoperations : Project root found at: /home/ahmedkhamessi/aws/code/elastic-beanstalk/myapp
2021-02-08 15:35:27,589 (DEBUG) ebcli.core.fileoperations : Project root found at: /home/ahmedkhamessi/aws/code/elastic-beanstalk/myapp
2021-02-08 15:35:27,592 (DEBUG) ebcli.core.fileoperations : Project root found at: /home/ahmedkhamessi/aws/code/elastic-beanstalk/myapp
2021-02-08 15:35:27,596 (DEBUG) ebcli.core.fileoperations : Project root found at: /home/ahmedkhamessi/aws/code/elastic-beanstalk/myapp
2021-02-08 15:35:27,599 (DEBUG) ebcli.core.fileoperations : Project root found at: /home/ahmedkhamessi/aws/code/elastic-beanstalk/myapp
2021-02-08 15:35:27,602 (DEBUG) ebcli.core.fileoperations : Project root found at: /home/ahmedkhamessi/aws/code/elastic-beanstalk/myapp
2021-02-08 15:35:27,606 (DEBUG) ebcli.core.fileoperations : Project root found at: /home/ahmedkhamessi/aws/code/elastic-beanstalk/myapp
2021-02-08 15:35:27,610 (DEBUG) ebcli.core.fileoperations : Project root found at: /home/ahmedkhamessi/aws/code/elastic-beanstalk/myapp
2021-02-08 15:35:27,613 (DEBUG) ebcli.core.fileoperations : Project root found at: /home/ahmedkhamessi/aws/code/elastic-beanstalk/myapp
2021-02-08 15:35:27,616 (DEBUG) ebcli.core.fileoperations : Project root found at: /home/ahmedkhamessi/aws/code/elastic-beanstalk/myapp
2021-02-08 15:35:27,619 (DEBUG) ebcli.lib.elasticbeanstalk : Inside get_available_solution_stacks api wrapper
2021-02-08 15:35:27,619 (DEBUG) ebcli.lib.aws : Creating new Botocore Session
2021-02-08 15:35:27,619 (DEBUG) ebcli.lib.aws : Botocore version: 1.19.63
2021-02-08 15:35:27,634 (DEBUG) ebcli.lib.aws : Creating new Botocore Client for elasticbeanstalk
2021-02-08 15:35:27,676 (DEBUG) ebcli.lib.aws : Successfully created session for elasticbeanstalk
2021-02-08 15:35:27,676 (DEBUG) ebcli.lib.aws : Making api call: (elasticbeanstalk, list_available_solution_stacks) to region: us-east-2 with args:{}
2021-02-08 15:35:28,950 (DEBUG) ebcli.lib.aws : API call finished, status = 200
2021-02-08 15:35:28,951 (DEBUG) ebcli.lib.aws : Response: {'SolutionStacks': ['64bit Amazon Linux 2018.03 v2.17.3 running Go 1.15.7', '64bit Amazon Linux 2018.03 v4.17.2 running Node.js', '64bit Amazon Linux 2018.03 v2.25.0 running Multi-container Docker 19.03.13-ce (Generic)', '64bit Amazon Linux 2018.03 v2.11.3 running Java 8', '64bit Amazon Linux 2018.03 v2.11.3 running Java 7', '64bit Amazon Linux 2018.03 v2.12.3 running Ruby 2.6 (Puma)', '64bit Amazon Linux 2018.03 v2.12.3 running Ruby 2.5 (Puma)', '64bit Amazon Linux 2018.03 v2.12.3 running Ruby 2.4 (Puma)', '64bit Amazon Linux 2018.03 v2.12.3 running Ruby 2.6 (Passenger Standalone)', '64bit Amazon Linux 2018.03 v2.12.3 running Ruby 2.5 (Passenger Standalone)', '64bit Amazon Linux 2018.03 v2.12.3 running Ruby 2.4 (Passenger Standalone)', '64bit Amazon Linux 
2018.03 v2.12.0 running Ruby 2.3 (Puma)', '64bit Amazon Linux 2018.03 v2.12.0 running Ruby 2.2 (Puma)', '64bit Amazon Linux 2018.03 v2.12.0 running Ruby 2.1 (Puma)', '64bit Amazon Linux 2018.03 v2.12.0 running Ruby 2.0 (Puma)', '64bit Amazon Linux 2018.03 v2.12.0 running Ruby 2.3 (Passenger Standalone)', '64bit Amazon Linux 2018.03 v2.12.0 running Ruby 2.2 (Passenger Standalone)', '64bit Amazon Linux 2018.03 v2.12.0 running Ruby 2.1 (Passenger Standalone)', '64bit Amazon Linux 2018.03 v2.12.0 running Ruby 2.0 (Passenger Standalone)', '64bit Amazon Linux 2018.03 v2.12.0 running Ruby 1.9.3', '64bit Amazon Linux 2018.03 v2.16.4 running Docker 19.03.13-ce', '64bit Debian jessie v2.16.0 running Go 1.4 (Preconfigured - Docker)', '64bit Debian jessie v2.16.0 running Go 1.3 (Preconfigured - Docker)', '64bit Amazon Linux 2018.03 v3.4.3 running Tomcat 8.5 Java 8', '64bit Amazon Linux 2018.03 v3.4.3 running Tomcat 7 Java 7', '64bit Amazon Linux 2018.03 v3.4.0 running Tomcat 8 Java 8', '64bit Amazon Linux 2018.03 v3.4.0 running Tomcat 7 Java 6', '64bit Debian jessie v2.16.0 running Python 3.4 (Preconfigured - Docker)', '64bit Amazon Linux 2018.03 v2.9.14 running PHP 7.2', '64bit Amazon Linux 2018.03 v2.9.14 running PHP 7.3', '64bit Amazon Linux 2018.03 v2.9.11 running PHP 5.4', '64bit Amazon Linux 2018.03 v2.9.11 running PHP 5.5', '64bit Amazon Linux 2018.03 v2.9.11 running PHP 5.6', '64bit Amazon Linux 2018.03 v2.9.11 running PHP 7.0', '64bit Amazon Linux 2018.03 v2.9.11 
running PHP 7.1', '64bit Amazon Linux 2018.03 v2.6.29 running Packer 1.0.3', '64bit Amazon Linux 2018.03 v2.9.18 running Python 3.6', '64bit Amazon Linux 2018.03 v2.9.15 running Python 3.4', '64bit Amazon Linux 2018.03 v2.9.15 running Python', '64bit Amazon Linux 2018.03 v2.9.15 running Python 2.7', '64bit Amazon Linux 2018.03 v2.16.4 running GlassFish 5.0 Java 8 (Preconfigured - Docker)', '64bit Amazon Linux 2 v3.2.2 running Ruby 2.7', '64bit Amazon Linux 2 v3.2.2 running Ruby 2.6', '64bit Amazon Linux 2 v3.2.2 running Ruby 2.5', '64bit Amazon Linux 2 v3.1.5 running Go 1', '64bit Amazon Linux 2 v4.1.5 running Tomcat 8.5 Corretto 11', '64bit Amazon Linux 2 v4.1.5 running Tomcat 8.5 Corretto 8', '64bit Amazon Linux 2 v4.1.5 running Tomcat 7 Corretto 11', '64bit Amazon Linux 2 v4.1.5 running Tomcat 7 Corretto 8', '64bit Amazon Linux 2 v3.1.5 running Corretto 11', '64bit Amazon Linux 2 v3.1.5 running Corretto 8', '64bit Amazon Linux 2 v2.1.2 running .NET Core', '64bit Amazon Linux 2 v5.2.5 running Node.js 12', '64bit Amazon Linux 2 v5.2.5 running Node.js 10', '64bit Amazon Linux 2 v3.2.4 running Docker', '64bit Amazon Linux 2 v3.1.5 running PHP 7.4', '64bit Amazon Linux 2 v3.1.5 running PHP 7.3', '64bit Amazon Linux 2 v3.1.5 running PHP 7.2', '64bit Amazon Linux 2 v3.1.5 running Python 3.7', '64bit Windows Server Core 2019 v2.6.2 running IIS 10.0', '64bit Windows Server 2019 v2.6.2 running IIS 10.0', '64bit Windows Server Core 2016 v2.6.2 running IIS 10.0', '64bit Windows Server 2016 v2.6.2 running IIS 10.0', '64bit Windows Server Core 2012 R2 v2.6.2 running IIS 8.5', '64bit Windows Server 2012 R2 v2.6.2 running IIS 8.5', '64bit Windows Server Core 2016 v1.2.0 running IIS 10.0', '64bit Windows Server 2016 v1.2.0 running IIS 10.0', '64bit Windows Server 2012 R2 v1.2.0 running IIS 8.5', '64bit Windows Server 2012 running IIS 8', '64bit Windows Server 2012 R2 running IIS 8.5', '64bit Windows Server Core 2012 R2 running IIS 8.5', '64bit Windows Server Core 2012 R2 v1.2.0 running IIS 8.5', '64bit Windows Server 2012 v1.2.0 running IIS 8'], 'SolutionStackDetails': [{'SolutionStackName': '64bit Amazon Linux 2018.03 v2.17.3 running Go 1.15.7', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v4.17.2 running Node.js', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.25.0 running Multi-container Docker 19.03.13-ce (Generic)', 'PermittedFileTypes': ['zip', 'json']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.11.3 running Java 8', 'PermittedFileTypes': ['jar', 'zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.11.3 running Java 7', 'PermittedFileTypes': ['jar', 'zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.12.3 running Ruby 2.6 (Puma)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.12.3 running Ruby 2.5 (Puma)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.12.3 running Ruby 2.4 (Puma)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.12.3 running Ruby 2.6 (Passenger Standalone)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.12.3 running Ruby 2.5 (Passenger Standalone)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.12.3 running Ruby 2.4 (Passenger Standalone)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit 
Amazon Linux 2018.03 v2.12.0 running Ruby 2.3 (Puma)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.12.0 running Ruby 2.2 (Puma)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.12.0 running Ruby 2.1 (Puma)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.12.0 running Ruby 2.0 (Puma)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.12.0 running Ruby 2.3 (Passenger Standalone)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.12.0 running Ruby 2.2 (Passenger Standalone)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.12.0 running Ruby 2.1 (Passenger Standalone)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.12.0 running Ruby 2.0 (Passenger Standalone)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.12.0 running Ruby 1.9.3', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.16.4 running Docker 19.03.13-ce', 'PermittedFileTypes': []}, {'SolutionStackName': '64bit Debian jessie v2.16.0 running Go 1.4 (Preconfigured - Docker)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Debian jessie v2.16.0 running Go 1.3 (Preconfigured - Docker)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v3.4.3 running Tomcat 8.5 Java 8', 'PermittedFileTypes': ['war', 'zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v3.4.3 running Tomcat 7 Java 7', 'PermittedFileTypes': ['war', 'zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v3.4.0 running Tomcat 8 Java 8', 'PermittedFileTypes': ['war', 'zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v3.4.0 running Tomcat 7 Java 6', 'PermittedFileTypes': ['war', 'zip']}, {'SolutionStackName': '64bit Debian jessie v2.16.0 running Python 3.4 (Preconfigured - Docker)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.9.14 running PHP 7.2', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.9.14 running PHP 7.3', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.9.11 running PHP 5.4', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.9.11 running PHP 5.5', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.9.11 running PHP 5.6', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.9.11 running PHP 7.0', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.9.11 running PHP 7.1', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.6.29 running Packer 1.0.3', 'PermittedFileTypes': []}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.9.18 running Python 3.6', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.9.15 running Python 3.4', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.9.15 running Python', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 
v2.9.15 running Python 2.7', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2018.03 v2.16.4 running GlassFish 5.0 Java 8 (Preconfigured - 
Docker)', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v3.2.2 running Ruby 2.7', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v3.2.2 running Ruby 2.6', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v3.2.2 running Ruby 2.5', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v3.1.5 running Go 1', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v4.1.5 running Tomcat 8.5 Corretto 11', 'PermittedFileTypes': ['war', 'zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v4.1.5 running Tomcat 8.5 Corretto 8', 'PermittedFileTypes': ['war', 'zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v4.1.5 running Tomcat 7 Corretto 11', 'PermittedFileTypes': ['war', 'zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v4.1.5 running Tomcat 7 Corretto 8', 'PermittedFileTypes': ['war', 'zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v3.1.5 running Corretto 11', 'PermittedFileTypes': ['jar', 'zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v3.1.5 running Corretto 8', 'PermittedFileTypes': ['jar', 'zip']}, 
{'SolutionStackName': '64bit Amazon Linux 2 v2.1.2 running .NET Core', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v5.2.5 running Node.js 12', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v5.2.5 running Node.js 10', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v3.2.4 running Docker', 'PermittedFileTypes': []}, {'SolutionStackName': '64bit Amazon Linux 2 v3.1.5 running PHP 7.4', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v3.1.5 running PHP 7.3', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v3.1.5 running PHP 7.2', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Amazon Linux 2 v3.1.5 running Python 3.7', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server Core 2019 v2.6.2 running IIS 10.0', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server 2019 v2.6.2 running IIS 10.0', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server Core 2016 v2.6.2 running IIS 10.0', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server 2016 v2.6.2 running IIS 10.0', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server Core 2012 R2 v2.6.2 running IIS 8.5', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server 2012 R2 v2.6.2 running IIS 8.5', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server Core 2016 v1.2.0 running IIS 10.0', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server 2016 v1.2.0 running 
IIS 10.0', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server 2012 R2 v1.2.0 running IIS 8.5', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server 2012 running IIS 8', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server 2012 R2 running IIS 8.5', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server Core 2012 R2 running IIS 8.5', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows 
Server Core 2012 R2 v1.2.0 running IIS 8.5', 'PermittedFileTypes': ['zip']}, {'SolutionStackName': '64bit Windows Server 2012 v1.2.0 running IIS 8', 'PermittedFileTypes': ['zip']}], 'ResponseMetadata': {'RequestId': 'd35d17ec-97c7-435e-94dd-22974edbec4f', 'HTTPStatusCode': 200, 'date': 'Mon, 08 Feb 2021 14:35:28 GMT', 'RetryAttempts': 0}}
2021-02-08 15:35:28,952 (DEBUG) ebcli.lib.elasticbeanstalk : Solution Stack result size = 73
2021-02-08 15:35:28,989 (DEBUG) ebcli.lib.elasticbeanstalk : Inside list_platform_versions api wrapper
2021-02-08 15:35:28,989 (DEBUG) ebcli.lib.aws : Making api call: (elasticbeanstalk, list_platform_versions) to region: us-east-2 with args:{'Filters': [{'Type': 'PlatformOwner', 'Operator': '=', 'Values': ['self']}]}
2021-02-08 15:35:29,175 (DEBUG) ebcli.lib.aws : API call finished, status = 200
2021-02-08 15:35:29,176 (DEBUG) ebcli.lib.aws : Response: {'PlatformSummaryList': [], 'ResponseMetadata': {'RequestId': '4a9e5979-080c-4e6a-8331-6be1ba804655', 'HTTPStatusCode': 200, 'date': 'Mon, 08 Feb 2021 14:35:28 GMT', 'RetryAttempts': 0}}
2021-02-08 15:35:29,176 (INFO) eb : Traceback (most recent call last):
  File "/home/ahmedkhamessi/.local/lib/python3.8/site-packages/ebcli/core/ebrun.py", line 62, in run_app
    app.run()
  File "/home/ahmedkhamessi/.local/lib/python3.8/site-packages/cement/core/foundation.py", line 797, in run
    return_val = self.controller._dispatch()
  File "/home/ahmedkhamessi/.local/lib/python3.8/site-packages/cement/core/controller.py", line 472, in _dispatch
    return func()
  File "/home/ahmedkhamessi/.local/lib/python3.8/site-packages/cement/core/controller.py", line 478, in _dispatch
    return func()
  File "/home/ahmedkhamessi/.local/lib/python3.8/site-packages/ebcli/controllers/config.py", line 93, in put
    platform = solution_stack_ops.find_solution_stack_from_string(platform)
  File "/home/ahmedkhamessi/.local/lib/python3.8/site-packages/ebcli/operations/solution_stack_ops.py", line 103, in find_solution_stack_from_string
    raise NotFoundError(alerts['platform.invalidstring'].format(solution_string))
ebcli.objects.exceptions.NotFoundError: Elastic Beanstalk can't find a platform version that matches "PHP 7.4 running on 64bit Amazon Linux 2".

### Expected result

I expected the configuration to be updated

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 18.4 LTS
2. EBCLI version: EB CLI 3.19.3 (Python 3.8.2)

**Comment by Palakpatel67** [comment] 2021-02-08 16:50
@ahmedkhammessi thanks for reporting this issue. It is appear to be duplicate of [issue #32](https://github.com/aws/aws-elastic-beanstalk-cli/issues/32). We have taken a note of this issue and working on fixing this. In the meantime here is a workaround:
```
$ eb init --platform "arn:aws:elasticbeanstalk:eu-west-1::platform/PHP 7.4 running on 64bit Amazon Linux 2/3.0.1"
```

Closing this issue here.

**Closed by Palakpatel67** 2021-02-08 16:50 UTC
