### ISSUE TITLE
eb create disregards .gitignore

### ISSUE THREAD

**Issue by owurman** [aws/aws-elastic-beanstalk-cli#42] opened 2020-08-06 18:03 UTC
### Description

eb deploy takes into consideration both .gitignore and .ebignore, but eb create seems to disregard .gitignore

### Steps to reproduce

Have a lot of data (>512 MB) in a subdirectory that is in .gitignore
eb create will fail because of the size
Add the subdirectory to .ebignore as well
eb create will succeed

### Observed result

Files in .gitignore are packaged for initial app upload

### Expected result

.gitignore is taken into consideration, as it is during subsequent eb deploy invocatoins

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS
2. EBCLI version: 3.18.2 (Python 3.8.5)

**Comment by Palakpatel67** [comment] 2020-11-19 17:22
@owurman thanks for reporting this issue. We will look into it and post any updates here.

**Comment by Palakpatel67** [comment] 2020-12-17 00:55
@owurman I have not been able to reproduce the issue. Few things to note,
From the [AWS EB docs](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3-configuration.html#eb-cli3-ebignore:~:text=If%20.ebignore%20isn't%20present%2C%20but%20.gitignore,the%20EB%20CLI%20doesn't%20read%20.gitignore.), If `.ebignore` isn't present, but .`gitignore` is, the EB CLI ignores files specified in `.gitignore`. If .`ebignore` is present, the EB CLI doesn't read `.gitignore`.

So If you have some file/directory in your `.gitignore` (because you don't want to commit it), create an .ebignore file and only add files that you don't want to be uploaded on your instances.

**Comment by owurman** [comment] 2020-12-17 01:05
That's probably it. I have a .ebignore file and probably did at the time I
ran into the issue, so it's expected that .gitignore isn't being read.

Thanks,
Oded

---
Oded Wurman, CEO
Acid Remap LLC
oded@acidremap.com

**Comment by Palakpatel67** [comment] 2020-12-17 01:16
no problem! 
Closing this issue. thanks!

**Closed by Palakpatel67** 2020-12-17 01:16 UTC
