### ISSUE TITLE
C:\HelloWorld>eb config put prod ERROR: NotFoundError - Elastic Beanstalk can't find a platform version that matches "PHP 7.4 running on 64bit Amazon Linux 2".

### ISSUE THREAD

**Issue by Periyasamypps** [aws/aws-elastic-beanstalk-cli#36] opened 2020-06-23 22:08 UTC
### Description

Briefly describe the bug you are facing.

### Steps to reproduce

Provide steps to replicate.

### Observed result

Please provide command output with `--debug` flag set.

### Expected result

Describe what you expected.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
Windows
`Add --debug flag to command you are running`

**Comment by halcarleton** [comment] 2020-06-24 19:07
This is appears to be a duplicate of https://github.com/aws/aws-elastic-beanstalk-cli/issues/32

**Closed by halcarleton** 2020-06-24 19:07 UTC
